=== stefilova/IST-prvi-projekat/adresar.dtd
<!ELEMENT Adresar (Osoba+, Kompanija+)>
<!ELEMENT Osoba (PunoIme, DatumRodjenja, Adresa, Telefon, Email+)>
<!ELEMENT PunoIme (Ime, SrednjeIme?, Prezime+)>
<!ELEMENT Ime (#PCDATA)>
<!ELEMENT SrednjeIme (#PCDATA)>
<!ELEMENT Prezime (#PCDATA)>
<!ELEMENT DatumRodjenja (Dan, Mesec, Godina)>
<!ELEMENT Dan (#PCDATA)>
<!ELEMENT Mesec (#PCDATA)>
<!ELEMENT Godina (#PCDATA)>
<!ELEMENT Adresa (Ulica, Broj, Grad, Drzava)>
<!ELEMENT Ulica (#PCDATA)>
<!ELEMENT Broj (#PCDATA)>
<!ELEMENT Grad (#PCDATA)>
<!ELEMENT Drzava (#PCDATA)>
<!ELEMENT Telefon (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT Kompanija (Naziv, Adresa, Telefon, Email+)>
<!ELEMENT Naziv (#PCDATA)>
<!ATTLIST Osoba id ID #REQUIRED>
<!ATTLIST Kompanija id ID #REQUIRED>
<!ATTLIST Adresa tip (privremena|stalna) "privremena">
<!ATTLIST Telefon tip (mobilni|fiksni) #REQUIRED>
<!ATTLIST Email tip (privatni|sluzbeni) #REQUIRED>

=== stefilova/IST-prvi-projekat/adresar.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE note SYSTEM "adresar.dtd">
<Adresar>
    <Osoba id="150">
    <PunoIme>
        <Ime>Stefan</Ime>
        <SrednjeIme>Radislav</SrednjeIme>
        <Prezime>Budimirovic</Prezime>
    </PunoIme>
    <DatumRodjenja>
        <Dan>28</Dan>
        <Mesec>Januar</Mesec>
        <Godina>1995</Godina>
    </DatumRodjenja>
    <Adresa tip="privremena">
        <Ulica>Francuska</Ulica>
        <Broj>32A</Broj>
        <Grad>Beograd</Grad>
        <Drzava>Srbija</Drzava>
    </Adresa>
    <Telefon tip="mobilni">0611891695</Telefon>
    <Email tip="sluzbeni">sb@sajtic.rs</Email>
    </Osoba>
    <Kompanija id="komp15-11">
        <Naziv>PrvaKompanija</Naziv>
        <Adresa tip="stalna">
            <Ulica>Francuska</Ulica>
            <Broj>32A</Broj>
            <Grad>Beograd</Grad>
            <Drzava>Srbija</Drzava>
        </Adresa>
        <Telefon tip="fiksni">011/222-567</Telefon>
        <Email tip="sluzbeni">sales@company.rs</Email>
    </Kompanija>
</Adresar>
